/*---------------------------------------------------------------------------------------------
 *  CS2 Inventory Simulator — economy data packager
 *
 *  Bundles the CS2 economy items + English item names into static modules under
 *  src/data/ so the Worker does not have to ship the 4.7 MB item table by
 *  requiring it from @ianlucas/cs2-lib item-by-item at runtime. Output sizes
 *  (gzip) are printed so you can watch the 3 MB Worker budget.
 *
 *  Output:
 *    src/data/items.ts       — CS2Item[] as a default export (~1.7 MB raw, ~658 KB gzip)
 *    src/data/item-names.ts  — Record<string, string> id -> English name (~500 KB raw, ~193 KB gzip)
 *--------------------------------------------------------------------------------------------*/

import { CS2_ITEMS } from "@ianlucas/cs2-lib";
import { english } from "@ianlucas/cs2-lib/translations/english";
import { gzipSync } from "node:zlib";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = resolve(rootDir, "src/data");

function gzipKb(text: string) {
  return (gzipSync(Buffer.from(text, "utf-8")).byteLength / 1024).toFixed(1);
}

function write(file: string, content: string, label: string) {
  writeFileSync(file, content, "utf-8");
  console.log(
    `[build:data] ${label.padEnd(22)} ${(Buffer.byteLength(content) / 1024).toFixed(0).padStart(5)} KB raw  ${gzipKb(content).padStart(6)} KB gzip`
  );
}

mkdirSync(dataDir, { recursive: true });

// --- items.ts (CS2Item array) ------------------------------------------------
const itemsJson = JSON.stringify(CS2_ITEMS);
write(
  resolve(dataDir, "items.ts"),
  [
    "// AUTO-GENERATED by scripts/generate-economy-data.ts — do not edit.",
    "// @ts-nocheck",
    "export default " + itemsJson + ";",
    ""
  ].join("\n"),
  "src/data/items.ts"
);

// --- item-names.ts (id -> English name) --------------------------------------
const names: Record<string, string> = {};
for (const [id, translation] of Object.entries(english)) {
  const name = translation?.name;
  if (name !== undefined && name.length > 0) {
    names[id] = name;
  }
}
write(
  resolve(dataDir, "item-names.ts"),
  [
    "// AUTO-GENERATED by scripts/generate-economy-data.ts — do not edit.",
    "// @ts-nocheck",
    "export const itemNames = " + JSON.stringify(names) + ";",
    ""
  ].join("\n"),
  "src/data/item-names.ts"
);

console.log("[build:data] done");